---
name: Docker build
on: [push]

jobs:
  build:
    name: Checkout and login
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        id: docker-login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push image
        id: docker-build
        env:
          IMAGE_NAME: alpine-base
          LOGIN_SERVER: docker.pkg.github.com
          IMAGE_TAG: ${{ github.sha }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          docker build -t "${LOGIN_SERVER}/${GITHUB_REPO}/${IMAGE_NAME}:${IMAGE_TAG}" .
          docker image tag ${LOGIN_SERVER}/${GITHUB_REPO}/${IMAGE_NAME}:${IMAGE_TAG} ${LOGIN_SERVER}/${GITHUB_REPO}/${IMAGE_NAME}:latest
          docker push ${LOGIN_SERVER}/${GITHUB_REPO}/${IMAGE_NAME}:${IMAGE_TAG}
          docker push ${LOGIN_SERVER}/${GITHUB_REPO}/${IMAGE_NAME}:latest
          echo "::set-output name=docker-server::${LOGIN_SERVER}"

      - name: Docker logout
        if: always()
        run: |
          docker logout ${{ steps.docker-build.outputs.docker-server }}

