---
name: Docker build
on: [push]

env:
  IMAGE_NAME: alpine-base
  LOGIN_SERVER: docker.pkg.github.com
  IMAGE_TAG: ${{ github.sha }}
  GITHUB_REPO: ${{ github.repository }}
  IMAGE_PATH: "${{ env.LOGIN_SERVER }}/${{ env.GITHUB_REPO }}/${{ env.IMAGE_NAME }}"

jobs:
  setup:
    name: Checkout and login
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        id: docker-login
        uses: azure/docker-login@v1
        with:
          login-server: ${LOGIN_SERVER}
          username: ${{ github.actor }}
          password: ${{ github.token }}

  build:
    name: Build image
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Build and push image
        id: docker-build
        run: |
          docker build -t ${IMAGE_PATH}:${IMAGE_TAG} .
